
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      tests:
          - my_test
          - sadfas_ad
      columns:
          - name: pnr_locator
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: snapshot
            description: "The snapshot"
